Fix missing x86_64 version of Zxing library by rebuild android lib with correct build variant. This fix the followinf error during build avd with x86_64 arch :
Caution: filename not matched:  jni/x86_64/*
ERROR: no JNI libs found for arch x86_64